backend:
  name: github
  repo: rasovica/rasovica-cms

media_folder: static/assets
public_folder: assets

collections:
  - name: recipe
    label: Recipes
    folder: markdown/recipe
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
